### ISSUE TITLE
Nice tool, any chance you can add it to conda?

### ISSUE THREAD

**Issue by AntonioBaeza** [schellt/backmap#6]
Nice tool, any chance you can add it to conda?

**Comment by schellt** [comment]
Sorry for the late reply and thanks a lot for using this script.
I don't plan to add it to conda. Basically, I don't think this is necessary as this is a wrapper only, that relies on certain dependencies which should be in your `$PATH`. As long as you have an environment with the dependencies it should work.
Let me know, if you have any issues while running `backmap.pl`.
